networks:
  wasp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

volumes:
  wasp-db-volume:

services:
  wasp-db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
      - .env-wasp-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - wasp-db-volume:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      wasp-network:

  wasp-core:
    build: .
    env_file:
      - .env
      - .env-wasp-core
    ports:
      - "8888:${SERVER_PORT}"
      - "8889:${MANAGEMENT_SERVER_PORT}"
    depends_on:
      wasp-db:
        condition: service_healthy
    networks:
      wasp-network: